### ISSUE TITLE
exception updating appdata

### ISSUE THREAD

**Issue by alexlarsson** [flathub/linux-store-backend#17]
Got this on the new deployment:
```
jan 22 14:23:45 webapps.flathub.org podman[5076]: 2019-01-22 14:23:45.431 ERROR 6 --- [pool-2-thread-1] o.flathub.api.service.UpdateServiceImpl  : Error updating info for app de.akaflieg_freiburg.cavok.add_hours_and_minutes
jan 22 14:23:45 webapps.flathub.org podman[5076]: java.lang.NullPointerException: null
jan 22 14:23:45 webapps.flathub.org podman[5076]: at org.freedesktop.appstream.AppdataComponent.findReleaseInfoByMostRecentAndLangIsDefault(AppdataComponent.java:595) ~[appstream-appdata-0.4.2.jar!/:na]
jan 22 14:23:45 webapps.flathub.org podman[5076]: at org.flathub.api.service.UpdateServiceImpl.setReleaseInfo(UpdateServiceImpl.java:537) [classes!/:0.6.5]
jan 22 14:23:45 webapps.flathub.org podman[5076]: at org.flathub.api.service.UpdateServiceImpl.updateAppInfo(UpdateServiceImpl.java:275) [classes!/:0.6.5]
jan 22 14:23:45 webapps.flathub.org podman[5076]: at org.flathub.api.service.UpdateServiceImpl.updateRepoInfo(UpdateServiceImpl.java:212) [classes!/:0.6.5]
jan 22 14:23:45 webapps.flathub.org podman[5076]: at org.flathub.api.service.UpdateServiceImpl.updateFlathubInfo(UpdateServiceImpl.java:110) [classes!/:0.6.5]
jan 22 14:23:45 webapps.flathub.org podman[5076]: at org.flathub.api.scheduledtasks.ScheduledTasks.updateFlathubInfo(ScheduledTasks.java:40) [classes!/:0.6.5]
jan 22 14:23:45 webapps.flathub.org podman[5076]: at org.flathub.api.scheduledtasks.ScheduledTasks$$FastClassBySpringCGLIB$$fadb339e.invoke(<generated>) [classes!/:0.6.5]
jan 22 14:23:45 webapps.flathub.org podman[5076]: at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) [spring-core-4.3.14.RELEASE.jar!/:4.3.14.RELEASE]
jan 22 14:23:45 webapps.flathub.org podman[5076]: at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:738) [spring-aop-4.3.14.RELEASE.jar!/:4.3.14.RELEASE]
jan 22 14:23:45 webapps.flathub.org podman[5076]: at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) [spring-aop-4.3.14.RELEASE.jar!/:4.3.14.RELEASE]
jan 22 14:23:45 webapps.flathub.org podman[5076]: at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99) [spring-tx-4.3.14.RELEASE.jar!/:4.3.14.RELEASE]
jan 22 14:23:45 webapps.flathub.org podman[5076]: at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:282) [spring-tx-4.3.14.RELEASE.jar!/:4.3.14.RELEASE]
jan 22 14:23:45 webapps.flathub.org podman[5076]: at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96) [spring-tx-4.3.14.RELEASE.jar!/:4.3.14.RELEASE]
jan 22 14:23:45 webapps.flathub.org podman[5076]: at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) [spring-aop-4.3.14.RELEASE.jar!/:4.3.14.RELEASE]
jan 22 14:23:45 webapps.flathub.org podman[5076]: at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:673) [spring-aop-4.3.14.RELEASE.jar!/:4.3.14.RELEASE]
jan 22 14:23:45 webapps.flathub.org podman[5076]: at org.flathub.api.scheduledtasks.ScheduledTasks$$EnhancerBySpringCGLIB$$1f87e864.updateFlathubInfo(<generated>) [classes!/:0.6.5]
jan 22 14:23:45 webapps.flathub.org podman[5076]: at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_181]
jan 22 14:23:45 webapps.flathub.org podman[5076]: at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_181]
jan 22 14:23:45 webapps.flathub.org podman[5076]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_181]
jan 22 14:23:45 webapps.flathub.org podman[5076]: at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_181]
jan 22 14:23:45 webapps.flathub.org podman[5076]: at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65) [spring-context-4.3.14.RELEASE.jar!/:4.3.14.RELEASE]
jan 22 14:23:45 webapps.flathub.org podman[5076]: at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.3.14.RELEASE.jar!/:4.3.14.RELEASE]
jan 22 14:23:45 webapps.flathub.org podman[5076]: at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.3.14.RELEASE.jar!/:4.3.14.RELEASE]
jan 22 14:23:45 webapps.flathub.org podman[5076]: at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_181]
jan 22 14:23:45 webapps.flathub.org podman[5076]: at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_181]
jan 22 14:23:45 webapps.flathub.org podman[5076]: at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_181]
jan 22 14:23:45 webapps.flathub.org podman[5076]: at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_181]
jan 22 14:23:45 webapps.flathub.org podman[5076]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_181]
jan 22 14:23:45 webapps.flathub.org podman[5076]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_181]
jan 22 14:23:45 webapps.flathub.org podman[5076]: at java.lang.Thread.run(Thread.java:748) [na:1.8.0_181]
```

**Comment by jgarciao** [comment]
I've identified the issue (incomplete release-info in appstream for this app) and fixed the bug in appstream-appdata-java. 

I still have to test it a little bit more before pushing a new version of the backend

Thanks for reporting the bug!

https://github.com/jgarciao/appstream-appdata-java/commit/32a97cb15efb86ae32eb17ce33444e9147117f8a
